Replacing a bash step with an apio common action.

diff --git a/.github/workflows/build-and-release.yaml b/.github/workflows/build-and-release.yaml
--- a/.github/workflows/build-and-release.yaml
+++ b/.github/workflows/build-and-release.yaml
@@ -154,34 +154,37 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ github.token }}
 
-
-
       # Scans recursively inside the .tgz packages.
       # See https://linux.die.net/man/1/clamscan
       - name: Scan the packages for viruses
         run: |
           clamscan -r --verbose --scan-archive=yes _packages/apio-verible-*.tgz
 
-      - name: Delete same tag pre-release if exist.
-        run: |
-          set -e
-          gh release list --limit 100
-          output=$(gh release view "$RELEASE_TAG" --json name,tagName,isDraft,isImmutable,isPrerelease 2>&1 || true)
-          echo $output
-          if [[ "$output" == "release not found" ]]; then
-            echo "Release $RELEASE_TAG does not exist, safe to continue."
-          elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "true" ]]; then
-            echo "Release $RELEASE_TAG exists and is a pre-release, deleting."
-            gh release delete "$RELEASE_TAG" --yes --cleanup-tag
-          elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "false" ]]; then
-            echo "Error: A stable release (non pre-release) already exists for tag $RELEASE_TAG."
-            exit 1
-          else
-            echo "Error determining if release $RELEASE_TAG exists"
-            exit 1
-          fi
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
+      - name: Ensure no conflicting release
+        uses: fpgawars/apio-workflows/.github/actions/ensure-no-conflicting-release@main
+        with:
+          release-tag: ${{ env.RELEASE_TAG }}
+
+      # - name: Delete same tag pre-release if exist.
+      #   run: |
+      #     set -e
+      #     gh release list --limit 100
+      #     output=$(gh release view "$RELEASE_TAG" --json name,tagName,isDraft,isImmutable,isPrerelease 2>&1 || true)
+      #     echo $output
+      #     if [[ "$output" == "release not found" ]]; then
+      #       echo "Release $RELEASE_TAG does not exist, safe to continue."
+      #     elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "true" ]]; then
+      #       echo "Release $RELEASE_TAG exists and is a pre-release, deleting."
+      #       gh release delete "$RELEASE_TAG" --yes --cleanup-tag
+      #     elif [[ "$(echo "$output" | jq -r '.isPrerelease')" == "false" ]]; then
+      #       echo "Error: A stable release (non pre-release) already exists for tag $RELEASE_TAG."
+      #       exit 1
+      #     else
+      #       echo "Error determining if release $RELEASE_TAG exists"
+      #       exit 1
+      #     fi
+      #   env:
+      #     GITHUB_TOKEN: ${{ github.token }}
 
       - name: Create the Release and upload files
         uses: softprops/action-gh-release@v2.2.2
