Changed the build workflow to refuse deleting same day stable (non pre-release) release if exists.

diff --git a/.github/workflows/build-and-release.yaml b/.github/workflows/build-and-release.yaml
--- a/.github/workflows/build-and-release.yaml
+++ b/.github/workflows/build-and-release.yaml
@@ -20,6 +20,10 @@ env:
   # -- See list at https://github.com/chipsalliance/verible/releases
   VERIBLE_RELEASE_TAG: "v0.0-3862-g936dfb1d"
 
+  # -- These are set later
+  RELEASE_TAG: ""
+  PACKAGE_TAG: ""
+
 jobs:
   # -- Build packages for all supported architectures and
   # -- export them in a release.
@@ -150,17 +154,31 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ github.token }}
 
-      # In case we overwrite and exiting release.
-      - name: Force tag update
-        run: |
-          git tag -f ${{env.RELEASE_TAG}}
-          git push origin -f ${{env.RELEASE_TAG}}
+
 
       # Scans recursively inside the .tgz packages.
       # See https://linux.die.net/man/1/clamscan
       - name: Scan the packages for viruses
         run: |
           clamscan -r --verbose --scan-archive=yes _packages/apio-verible-*.tgz
+
+      - name: Delete same tag pre-release if exist.
+        run: |
+          # Status values:
+          #   "false" - exists and is a release exists
+          #   "true"  - exists and is a pre-release
+          #   ""      - doesn't exist
+          status=$(gh release view "$RELEASE_TAG" --json isPrerelease -q .isPrerelease  || true)
+          echo "Status is [$status]"
+          if [[ "$status" == "false" ]]; then
+            echo "Error: A stable release (non pre-release) already exists for tag $RELEASE_TAG."
+            exit 1
+          elif [[ "$status" == "true" ]]; then
+            echo "Deleting existing pre-release and tag $RELEASE_TAG."
+            gh release delete "$RELEASE_TAG" --yes --cleanup-tag
+          fi
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
 
       - name: Create the Release and upload files
         uses: softprops/action-gh-release@v2.2.2
